name: python - on Push to main

on:
  push:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install reportlab pymongo openpyxl pandas bs4 selenium

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: Test unique codes and pdf generation
        run: python backend/code_pdf_tests.py