name: scrapers - on Push to main

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "scrapers/**"
      - "tests/**"

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest scrapy scrapyscript beautifulsoup4 selenium

      - name: Test the web scraping and physician verification
        run: pytest tests/test_scrapers.py
